from turtle import Turtle, Screen, Shape
from time import sleep
import turtle
screen = turtle.Screen()
cursor = turtle.Turtle()

def initialize():
    turtle.setup(800, 484)
    turtle.bgcolor("cyan")
    cursor.hideturtle()

def __startEmotion():
    turtle.reset()
    turtle.speed(0)

def __endEmotion():
    cursor.hideturtle()
    turtle.done()

def __startFunction():
    turtle.hideturtle()
    turtle.speed(0)
    turtle.penup()
    turtle.goto(0, 0)

def __drawEndFunction():
    turtle.reset()

def __drawEyes():
    __startFunction()
    openeyes = Shape("compound")
    turtle.begin_poly()
    turtle.goto(-80, 0)
    turtle.pendown()
    turtle.circle(15)
    turtle.penup()
    turtle.end_poly()
    lefteyeoutframe = turtle.get_poly()
    openeyes.addcomponent(lefteyeoutframe, "black", "cyan")
    turtle.begin_poly()
    turtle.penup()
    turtle.goto(-80, 0)
    turtle.pendown()
    turtle.circle(8)
    turtle.penup()
    turtle.end_poly()
    lefteyeinframe = turtle.get_poly()
    openeyes.addcomponent(lefteyeinframe, "cyan", "black")
    turtle.begin_poly()
    turtle.penup()
    turtle.goto(80, 0)
    turtle.pendown()
    turtle.circle(15)
    turtle.penup()
    turtle.end_poly()
    righteyeoutframe = turtle.get_poly()
    openeyes.addcomponent(righteyeoutframe, "black", "cyan")
    turtle.begin_poly()
    turtle.penup()
    turtle.goto(80, 0)
    turtle.pendown()
    turtle.circle(8)
    turtle.penup()
    turtle.end_poly()
    righteyeinframe = turtle.get_poly()
    openeyes.addcomponent(righteyeinframe, "cyan", "black")
    screen.addshape("OpenedEyes", openeyes)
    closeeyes = Shape("compound")
    turtle.begin_poly()
    turtle.goto(-80, 0)
    turtle.pendown()
    turtle.fd(28)
    turtle.left(90)
    turtle.fd(2)
    turtle.left(90)
    turtle.fd(28)
    turtle.left(90)
    turtle.fd(2)
    turtle.end_poly()
    leftcloseeye = turtle.get_poly()
    closeeyes.addcomponent(leftcloseeye, "black", "cyan")
    turtle.penup()
    turtle.begin_poly()
    turtle.goto(80, 0)
    turtle.pendown()
    turtle.left(90)
    turtle.fd(28)
    turtle.left(90)
    turtle.fd(2)
    turtle.left(90)
    turtle.fd(28)
    turtle.left(90)
    turtle.fd(2)
    turtle.end_poly()
    rightcloseeye = turtle.get_poly()
    closeeyes.addcomponent(rightcloseeye, "black", "cyan")
    screen.addshape("ClosedEyes", closeeyes)
    __drawEndFunction()

def __showEyes():
    __startFunction()
    __drawEyes()
    eyes = turtle.Turtle("OpenedEyes")
    eyes.speed(0)
    eyes.penup()
    eyes.left(90)
    eyes.goto(-5, 20)
    eyes.resizemode("user")
    eyes.shapesize(2, 3)

def __drawMouth():
    __startFunction()
    turtle.color("black", "black")
    turtle.begin_poly()
    turtle.begin_fill()
    turtle.pensize(10)
    turtle.circle(200, 60)
    turtle.end_fill()
    turtle.end_poly()
    lowerlips = turtle.get_poly()
    screen.addshape("LowerLips", lowerlips)
    turtle.color("cyan", "cyan")
    turtle.pensize(10)
    turtle.begin_poly()
    turtle.begin_fill()
    turtle.circle(160, 60)
    turtle.end_fill()
    turtle.end_poly()
    upperlips = turtle.get_poly()
    screen.addshape("UpperLips", upperlips)
    __drawEndFunction()

def __showMouth():
    __startFunction()
    __drawMouth()
    lowerlips = turtle.Turtle("LowerLips")
    lowerlips.speed(0)
    lowerlips.penup()
    lowerlips.goto(-100, -130)
    lowerlips.left(60)
    upperlips = turtle.Turtle("UpperLips")
    upperlips.color("cyan")
    upperlips.speed(0)
    upperlips.penup()
    upperlips.goto(-179, 45)

def __drawNose():
    __startFunction()
    turtle.color("black", "black")
    turtle.begin_poly()
    turtle.penup()
    turtle.pendown()
    turtle.begin_fill()
    turtle.circle(10)
    turtle.end_fill()
    turtle.end_poly()
    nose = turtle.get_poly()
    screen.addshape("Nose", nose)
    __drawEndFunction()

def __showNose():
    __startFunction()
    __drawNose()
    nosedraw = turtle.Turtle("Nose")
    nosedraw.speed(0)
    nosedraw.penup()
    nosedraw.goto(-10, 0)

def __drawEyeBrows():
    __startFunction()
    eyebrows = Shape("compound")
    turtle.begin_poly()
    turtle.penup()
    turtle.goto(-80, 0)
    turtle.left(10)
    turtle.pendown()
    turtle.fd(15)
    turtle.left(90)
    turtle.fd(5)
    turtle.left(90)
    turtle.fd(30)
    turtle.left(90)
    turtle.fd(5)
    turtle.left(90)
    turtle.fd(15)
    turtle.end_poly()
    leftbro = turtle.get_poly()
    eyebrows.addcomponent(leftbro, "black", "cyan")
    turtle.penup()
    turtle.right(10)
    turtle.goto(80, 0)
    turtle.begin_poly()
    turtle.left(180)
    turtle.right(10)
    turtle.fd(15)
    turtle.right(90)
    turtle.fd(5)
    turtle.right(90)
    turtle.fd(30)
    turtle.right(90)
    turtle.fd(5)
    turtle.right(90)
    turtle.fd(15)
    turtle.end_poly()
    rightbro = turtle.get_poly()
    eyebrows.addcomponent(rightbro, "black", "cyan")
    screen.addshape("EyeBrows", eyebrows)
    __drawEndFunction()

def __showEyeBrows():
    __startFunction()
    __drawEyeBrows()
    browsdraw = turtle.Turtle("EyeBrows")
    browsdraw.speed(0)
    browsdraw.penup()
    browsdraw.left(90)
    browsdraw.goto(-5, 130)
    browsdraw.resizemode("user")
    browsdraw.shapesize(2, 3)

def __blinkEyes():
    __startFunction()
    __drawEyes()
    openeyes = turtle.Turtle("OpenedEyes")
    openeyes.speed(0)
    openeyes.penup()
    openeyes.left(90)
    openeyes.goto(-5, 20)
    openeyes.resizemode("user")
    openeyes.shapesize(2, 3)
    closeeyes = turtle.Turtle("ClosedEyes")
    closeeyes.speed(0)
    closeeyes.penup()
    closeeyes.left(90)
    closeeyes.goto(-33, 57)
    closeeyes.resizemode("user")
    closeeyes.shapesize(2, 3)
    while 1:
        sleep(4)
        openeyes.hideturtle()
        closeeyes.showturtle()
        sleep(0.1)
        openeyes.showturtle()

def __talk():
    __startFunction()
    __drawMouth()
    lowerlips = turtle.Turtle("LowerLips")
    lowerlips.speed(0)
    lowerlips.penup()
    lowerlips.goto(-100, -130)
    lowerlips.left(60)
    upperlips = turtle.Turtle("UpperLips")
    upperlips.color("cyan")
    upperlips.speed(0)
    upperlips.penup()
    upperlips.goto(-179, 45)
    while 1:
        sleep(0.1)
        upperlips.hideturtle()
        sleep(0.1)
        upperlips.showturtle()

def normalEmotion():
    __startEmotion()
    __showMouth()
    __showNose()
    __showEyeBrows()
    __blinkEyes()
    __endEmotion()

def talkingEmotion():
    __startEmotion()
    __showEyes()
    __showEyeBrows()
    __showNose()
    __talk()
    __endEmotion()


